import InfoContent from "@/components/info/InfoContent";

const pages = {
  about:{ru:{title:"О магазине LUCHIK.CO",text:"Учебный интернет-магазин одежды. Здесь можно выбирать варианты товара, оформлять бронирование и общаться с магазином через личный кабинет."},en:{title:"About LUCHIK.CO",text:"A demo online clothing store where you can choose product variants, reserve orders, and contact the store through your account."}},
  delivery:{ru:{title:"Доставка",text:"При оформлении выберите курьера или пункт выдачи. Срок и стоимость подтверждает администратор в сообщении по заказу.",sections:[{title:"Курьер",text:"Адрес сохраняется в заказе. В демо-режиме курьер не вызывается, а статус меняется администратором."},{title:"Пункт выдачи",text:"В учебной версии используется демонстрационный вариант самовывоза без передачи данных реальной службе доставки."},{title:"Отслеживание",text:"Каждый заказ получает демонстрационный трек-номер. Его состояние следует за статусом заказа в личном кабинете."}]},en:{title:"Delivery",text:"Choose courier delivery or a pickup point at checkout. The administrator will confirm the delivery time and cost in an order message.",sections:[{title:"Courier",text:"The address is stored with the order. No real courier is dispatched in demo mode; the administrator updates the status."},{title:"Pickup point",text:"The training version uses a simulated pickup option and sends no details to a real delivery company."},{title:"Tracking",text:"Every order receives a demo tracking number that follows the order status in the customer account."}]}},
  returns:{ru:{title:"Возврат товара",text:"Неношеный товар можно вернуть в течение 30 дней. Сохраните упаковку и напишите администратору через уведомления заказа.",sections:[{title:"Срок",text:"Демонстрационная политика предполагает обращение в течение 30 дней после получения."},{title:"Состояние товара",text:"Товар считается подходящим для возврата, если не использовался и сохранил комплектность и упаковку."},{title:"Как обратиться",text:"Откройте заказ в личном кабинете и ответьте на сообщение администратора. Реальная отправка и возврат денег не выполняются."}]},en:{title:"Returns",text:"Unused items can be returned within 30 days. Keep the packaging and contact the administrator through your order notifications.",sections:[{title:"Return period",text:"The demo policy allows a request within 30 days after delivery."},{title:"Item condition",text:"An item is eligible when unused and kept complete with its original packaging."},{title:"How to request",text:"Open the order in your account and reply to the administrator. No real shipment or refund is performed."}]}},
  terms:{ru:{title:"Условия использования",text:"Оформление в текущей учебной версии является бронированием. Настоящее списание денежных средств не производится.",sections:[{title:"Назначение",text:"LUCHIK.CO используется для демонстрации интерфейса интернет-магазина, аккаунтов, каталога и административной панели."},{title:"Заказы",text:"Созданный заказ попадает в учебную базу и меняет демонстрационные остатки, но не создаёт обязательства по продаже или доставке."},{title:"Оплата",text:"Поля тестовой карты не передаются платёжной системе и не сохраняются. Используйте только вымышленные данные."}]},en:{title:"Terms and Conditions",text:"Checkout in this demo version creates a reservation. No real payment is charged.",sections:[{title:"Purpose",text:"LUCHIK.CO demonstrates a storefront, customer accounts, a catalog, and an administration dashboard."},{title:"Orders",text:"An order is stored in the training database and updates demo stock, but creates no obligation to sell or deliver goods."},{title:"Payment",text:"Demo card fields are not sent to a payment provider or stored. Use fictional details only."}]}},
  privacy:{ru:{title:"Политика конфиденциальности",text:"Данные аккаунта и заказа используются только для работы магазина. Пароли обрабатывает защищённая система Supabase Auth, и магазин их не видит.",sections:[{title:"Какие данные сохраняются",text:"Email, имя, контактные данные, адрес доставки, состав заказа, отзывы, вопросы и переписка по заказу."},{title:"Пароли",text:"Пароли передаются непосредственно Supabase Auth и хранятся только в защищённом виде. Администратор не может их просматривать."},{title:"Платёжные данные",text:"Тестовые номер карты, срок и CVC существуют только на странице до оформления и никогда не записываются в базу."}]},en:{title:"Privacy Policy",text:"Account and order details are used only to operate the store. Passwords are handled by Supabase Auth and are never visible to the store.",sections:[{title:"Data stored",text:"Email, name, contact details, delivery address, order contents, reviews, questions, and order messages."},{title:"Passwords",text:"Passwords go directly to Supabase Auth and are stored only in protected form. The administrator cannot view them."},{title:"Payment details",text:"Demo card number, expiry, and CVC exist only on the checkout page and are never stored in the database."}]}},
  support:{ru:{title:"Поддержка покупателей",text:"Задайте вопрос на странице товара или ответьте администратору в уведомлениях личного кабинета."},en:{title:"Customer Support",text:"Ask a question on a product page or reply to the administrator through notifications in your account."}},
  payments:{ru:{title:"Оплата",text:"Доступны бронирование без оплаты, демонстрационная карта и демонстрационный СБП. Реальная оплата пока не подключена.",sections:[{title:"Бронирование",text:"Создаёт заказ без платёжного шага и передаёт его администратору со статусом «Новый»."},{title:"Тестовая карта",text:"Проверяется только формат вымышленных реквизитов. Списания, проверки банка и сохранения номера карты нет."},{title:"Демонстрационный СБП",text:"Имитирует успешное подтверждение после согласия пользователя. QR-код и банковское приложение не используются."}]},en:{title:"Payments",text:"Reservation without payment, a demo bank card, and a demo fast-payment option are available. Real payments are not connected yet.",sections:[{title:"Reservation",text:"Creates an order without payment and sends it to the administrator with New status."},{title:"Demo card",text:"Only the format of fictional details is checked. There is no charge, bank verification, or card-number storage."},{title:"Demo fast payment",text:"Simulates confirmation after user consent. No QR code or banking application is involved."}]}},
  sizes:{ru:{title:"Таблица размеров",text:"Small — небольшой, Medium — средний, Large — большой, X-Large — очень большой. Перед заказом сверяйтесь с описанием конкретного товара."},en:{title:"Size Guide",text:"Small, Medium, Large, and X-Large follow standard sizing. Check the measurements for the specific product before ordering."}},
};
export function generateStaticParams(){return Object.keys(pages).map((slug)=>({slug}));}
export default async function InfoPage({params}){const {slug}=await params;return <InfoContent page={pages[slug]||pages.support}/>;}
