create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'customer' check (role in ('customer', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text default '',
  category text not null,
  dress_style text,
  price numeric(10,2) not null check (price >= 0),
  old_price numeric(10,2),
  rating numeric(2,1) default 0,
  stock integer not null default 0 check (stock >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_variants (
  id uuid primary key default gen_random_uuid(),
  product_id bigint not null references public.products(id) on delete cascade,
  color_name text not null,
  color_hex text,
  size text not null,
  image_url text,
  stock integer not null default 0 check (stock >= 0),
  unique(product_id, color_name, size)
);

create table if not exists public.promo_codes (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  discount_percent integer not null check (discount_percent between 1 and 100),
  active boolean not null default true,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  status text not null default 'new' check (status in ('new','paid','processing','shipped','completed','cancelled')),
  subtotal numeric(10,2) not null,
  discount numeric(10,2) not null default 0,
  delivery_fee numeric(10,2) not null default 0,
  total numeric(10,2) not null,
  customer_email text,
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  color text,
  size text,
  quantity integer not null check (quantity > 0),
  unit_price numeric(10,2) not null
);

insert into public.promo_codes (code, discount_percent)
values ('SALE20', 20), ('SALE30', 30), ('SALE50', 50)
on conflict (code) do update set discount_percent = excluded.discount_percent;

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.product_variants enable row level security;
alter table public.promo_codes enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin') $$;

create policy "public reads active products" on public.products for select using (active or public.is_admin());
create policy "public reads variants" on public.product_variants for select using (true);
create policy "public reads active promos" on public.promo_codes for select using (active);
create policy "admins manage products" on public.products for all using (public.is_admin()) with check (public.is_admin());
create policy "admins manage variants" on public.product_variants for all using (public.is_admin()) with check (public.is_admin());
create policy "admins manage promos" on public.promo_codes for all using (public.is_admin()) with check (public.is_admin());
create policy "customers read own orders" on public.orders for select using (user_id = auth.uid() or public.is_admin());
create policy "customers create orders" on public.orders for insert with check (user_id = auth.uid() or user_id is null);
create policy "admins manage orders" on public.orders for all using (public.is_admin()) with check (public.is_admin());
create policy "customers read own order items" on public.order_items for select using (
  exists(select 1 from public.orders where orders.id = order_items.order_id and (orders.user_id = auth.uid() or public.is_admin()))
);
create policy "customers create order items" on public.order_items for insert with check (
  exists(select 1 from public.orders where orders.id = order_items.order_id and (orders.user_id = auth.uid() or orders.user_id is null))
);
create policy "admins manage order items" on public.order_items for all using (public.is_admin()) with check (public.is_admin());
